# Generated by Django 5.2 on 2026-02-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'verbose_name': 'Забег', 'verbose_name_plural': 'Забеги'},
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Инициирован'), ('in_progress', 'Стартовал'), ('finished', 'Закончил')], default='init', max_length=20, verbose_name='Статус забега'),
        ),
        migrations.AlterField(
            model_name='run',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Атлет'),
        ),
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
