# Generated by Django 5.2 on 2026-03-07 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_athlete_alter_run_status_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1)),
                ('goals', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_info', to=settings.AUTH_USER_MODEL, verbose_name='Атлет')),
            ],
            options={
                'verbose_name': 'Информация об атлете',
                'verbose_name_plural': 'Информация об атлетах',
            },
        ),
    ]
