# Generated by Django 5.2 on 2026-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_athleteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
