# Generated by Django 5.2 on 2026-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0006_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="distance",
            field=models.FloatField(default=0, verbose_name="Дистанция, км"),
        ),
    ]
