# Generated by Django 5.2 on 2026-06-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_run_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('uid', models.CharField(max_length=255, verbose_name='UID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('picture', models.URLField(verbose_name='Изображение')),
                ('value', models.IntegerField(verbose_name='Ценность')),
            ],
            options={
                'verbose_name': 'Коллекционный предмет',
                'verbose_name_plural': 'Коллекционные предметы',
            },
        ),
    ]
