# Generated by Django 5.2 on 2026-07-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0, verbose_name='Пройденное расстояние, км'),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0, verbose_name='Скорость, м/с'),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0, verbose_name='Средняя скорость, м/с'),
        ),
    ]
